-- Common usage
ON_OPTION = "on"
OFF_OPTION = "off"

-- Role identity Keys
GM_KEY = "GM"
CHAR_KEY = "CHAR"

-- Generic Commands Action Keys
GENERICS_parametersGet = "parametersGet"
GENERICS_isValueNeeded = "isValueNeeded"
GENERICS_isParametersNeeded = "isParametersNeeded"
GENERICS_isTargetCheckNeeded = "isTargetCheckNeeded"
GENERICS_command = "command"
GENERICS_message = "message"

-- Spells Keys
GM_displayAccountGMLevelCommand = "displayAccountLevel"
GM_flyModeCommand = "flyMode"
GM_godModeCommand = "godMode"
GM_acceptWhispersCommand = "acceptWhispers"
GM_visibilityCommand = "visibility"
GM_cheatTaxiCommand = "cheatTaxi"
GM_cheatExploreMapsCommand = "cheatExploreMaps"
GM_cheatWaterWalkCommand = "cheatWaterWalk"
GM_cheatNoCastTimeCommand = "cheatNoCastTime"
GM_cheatNoCooldownCommand = "cheatNoCooldown"
GM_accountIPLockCommand = "accountIPLock"
GM_GMListCommand = "GMList"
GM_GMInGameCommand = "GMInGame"
GM_GMNotifyCommand = "GMNotify"
GM_GMMessageCommand = "GMMessage"
GM_castCommand = "cast"
GM_castBackCommand = "castBack"
GM_castDistCommand = "castDist"
GM_castSelfCommand = "castSelf"
GM_castTargetCommand = "castTarget"
GM_teleportAddCommand = "teleportAdd"
GM_teleportDelCommand = "teleportDel"
GM_listItemCommand = "listItem"
GM_lookupTaxiCommand = "lookupTaxi"
GM_lookupZoneCommand = "lookupZone"
GM_goTaxiNodeCommand = "goTaxiNode"
GM_goTriggerCommand = "goTrigger"
GM_goXYCommand = "goXY"
GM_goXYZCommand = "goXYZ"
GM_goZoneXYCommand = "goZoneXY"
GM_petCreateCommand = "petCreate"
GM_petLearnCommand = "petLearn"
GM_petUnLearnCommand = "petUnLearn"
GM_petTalentsLearnCommand = "petTalentsLearn"
GM_bankCommand = "bank"
GM_dismountPlayerCommand = "dismountPlayer"
GM_playerSpeedCommand = "playerSpeed"
GM_playerScaleCommand = "playerScale"
GM_AllianceJailCommand = "allianceJail"
GM_HordeJailCommand = "hordeJail"

CHAR_reviveCommand = "revive"
CHAR_saveCommand = "save"
CHAR_kickCommand = "kick"
CHAR_cooldownCommand = "cooldown"
CHAR_GUIDCommand = "GUID"
CHAR_playerInfoCommand = "playerInfo"
CHAR_distanceCommand = "distance"
CHAR_dieCommand = "die"
CHAR_recallCommand = "recall"
CHAR_morphCommand = "morph"
CHAR_morphResetCommand = "morphReset"

