-- Role identity Keys
GM_KEY = "GM"

-- Generic Spells Action Keys
GENERICS_parametersGet = "parametersGet"
GENERICS_isValueNeeded = "isValueNeeded"
GENERICS_isParametersNeeded = "isParametersNeeded"
GENERICS_isTargetCheckNeeded = "isTargetCheckNeeded"
GENERICS_command = "command"
GENERICS_message = "message"

-- Spells Keys
GM_displayAccountGMLevel = "displayAccountLevel"
GM_flyMode = "flyMode"
GM_godMode = "godMode"
GM_acceptWhispers = "acceptWhispers"
GM_visibility = "visibility"
GM_cheatTaxi = "cheatTaxi"
GM_cheatExploreMaps = "cheatExploreMaps"
GM_cheatWaterWalk = "cheatWaterWalk"
GM_cheatNoCastTime = "cheatNoCastTime"
GM_cheatNoCooldown = "cheatNoCooldown"
GM_accountIPLock = "accountIPLock"
GM_GMList = "GMList"
GM_GMInGame = "GMInGame"
GM_GMNotify = "GMNotify"
GM_GMMessage = "GMMessage"
GM_Cast = "Cast"
GM_CastBack = "CastBack"
GM_CastDist = "CastDist"
GM_CastSelf = "CastSelf"
GM_CastTarget = "CastTarget"
GM_TeleportAdd = "TeleportAdd"
GM_TeleportDel = "TeleportDel"
GM_ListItem = "ListItem"
GM_LookupTaxi = "LookupTaxi"
GM_LookupZone = "LookupZone"
GM_GoTaxiNode = "GoTaxiNode"
GM_GoTrigger = "GoTrigger"
GM_GoXY = "GoXY"
GM_GoXYZ = "GoXYZ"
GM_GoZoneXY = "GoZoneXY"
GM_PetCreate = "PetCreate"
GM_PetLearn = "PetLearn"
GM_PetUnLearn = "PetUnLearn"
GM_PetTalentsLearn = "PetTalentsLearn"
GM_DismountPlayer = "DismountPlayer"